Fixes requested in Pull Request

diff --git a/src/flash-image b/src/flash-image
--- a/src/flash-image
+++ b/src/flash-image
@@ -94,22 +94,22 @@ backup_mtd_partition() {
 	fi
 	
 	# I know this is bad, but we can't store this in /tmp if images are there due to space
-	_TEMPMOUNT="$(mktemp -d)"
-	if ! mount "/dev/sda1" "$_TEMPMOUNT" ; then
-		log "Could not mount /dev/sda1 to $_TEMPMOUNT"
-		rm -r ${_TEMPMOUNT}
+	_TEMP_MOUNT="$(mktemp -d)"
+	if ! mount "/dev/sda1" "$_TEMP_MOUNT" ; then
+		log "Could not mount /dev/sda1 to $_TEMP_MOUNT"
+		rm -r ${_TEMP_MOUNT}
 		return 1;
 	fi
 
 	# Do we know the mount point? We do this so all backups go to the same folder
 	if ! test -f "/tmp/backup_dir" ; then
 		I=1
-		while test -d "$_TEMPMOUNT/flashcast-backups/backup-${I}/" ; do
+		while test -d "$_TEMP_MOUNT/flashcast-backups/backup-${I}/" ; do
                 	I="$((I+1))"
 		done
-		dry_run "Would create $_TEMPMOUNT/flashcast-backups/backup-${I}"
+		dry_run "Would create $_TEMP_MOUNT/flashcast-backups/backup-${I}"
 		if test -z "$DRY_RUN" ; then
-			mkdir -p "$_TEMPMOUNT/flashcast-backups/backup-${I}"
+			mkdir -p "$_TEMP_MOUNT/flashcast-backups/backup-${I}"
 		fi
         	echo "flashcast-backups/backup-${I}" > /tmp/backup_dir
 	fi
@@ -121,9 +121,9 @@ backup_mtd_partition() {
         # 1: uses ALOT less space
         # 2: dumps of this partition do not write back properly
 	if test "${1}" = "userdata" ; then
-		dry_run "Would backup ${1} to $_TEMPMOUNT/$_BACKUPFOLDER/${1}.zip"
+		dry_run "Would backup ${1} to $_TEMP_MOUNT/$_BACKUPFOLDER/${1}.zip"
 		if test -z "$DRY_RUN" ; then
-			log "Backing Up ${1} to $_TEMPMOUNT/$_BACKUPFOLDER/${1}.zip"
+			log "Backing Up ${1} to $_TEMP_MOUNT/$_BACKUPFOLDER/${1}.zip"
 			_DATAFOLDER="$(mktemp -d)"
 			if ! mount "/dev/mtdblock5" "$_DATAFOLDER" ; then
 				log "Failed to Mount $_PARTITION to $_DATAFOLDER"
@@ -131,7 +131,7 @@ backup_mtd_partition() {
 				return 1;
 			else
 				cd $_DATAFOLDER
-				if ! zip -qry $_TEMPMOUNT/$_BACKUPFOLDER/${1}.zip ./* -x \*wpa_ctrl\* ; then
+				if ! zip -qry $_TEMP_MOUNT/$_BACKUPFOLDER/${1}.zip ./* -x \*wpa_ctrl\* ; then
 					fatal "Error while compressing contents of userdata, aborting."
 					return 1;
 				fi
@@ -142,22 +142,22 @@ backup_mtd_partition() {
 			fi
 		fi
 	else
-		dry_run "Would backup ${1} to $_TEMPMOUNT/$_BACKUPFOLDER/${1}.img"
+		dry_run "Would backup ${1} to $_TEMP_MOUNT/$_BACKUPFOLDER/${1}.img"
 		if test -z "$DRY_RUN" ; then
-			log "Backing Up ${1} to $_TEMPMOUNT/$_BACKUPFOLDER/${1}.img"
-			if ! nanddump -q -f "${_TEMPMOUNT}/${_BACKUPFOLDER}/${1}.img" "/dev/${_PARTITION}"; then
-				fatal "Error Saving ${1} to $_TEMPMOUNT/$_BACKUPFOLDER/${1}.img"
+			log "Backing Up ${1} to $_TEMP_MOUNT/$_BACKUPFOLDER/${1}.img"
+			if ! nanddump -q -f "${_TEMP_MOUNT}/${_BACKUPFOLDER}/${1}.img" "/dev/${_PARTITION}"; then
+				fatal "Error Saving ${1} to $_TEMP_MOUNT/$_BACKUPFOLDER/${1}.img"
 				return 1;
 			fi
 		fi
 	fi
 
 	#Do our own Cleanup
-	umount ${_TEMPMOUNT} && rm -r ${_TEMPMOUNT}
+	umount ${_TEMP_MOUNT} && rm -r ${_TEMP_MOUNT}
 }
 
 # restore_mtd_partition
-# Used to Restore dumps bade by backup_mtd_partition.
+# Used to Restore dumps made by backup_mtd_partition.
 #
 # Parameters:
 #   $1: The name (NOT number) of the MTD partition to restore.
@@ -172,20 +172,20 @@ restore_mtd_partition() {
 	fi
 	
 	# We need a mount point to get the images, and again, files are too big for /tmp
-	_TEMPMOUNT="$(mktemp -d)"
-	if ! mount "/dev/sda1" "$_TEMPMOUNT" ; then
-		log "Could not mount /dev/sda1 to $_TEMPMOUNT"
-		rm -r ${_TEMPMOUNT}
+	_TEMP_MOUNT="$(mktemp -d)"
+	if ! mount "/dev/sda1" "$_TEMP_MOUNT" ; then
+		log "Could not mount /dev/sda1 to $_TEMP_MOUNT"
+		rm -r ${_TEMP_MOUNT}
 		return 1;
 	fi
         
 	# Does the backup even exist?	
-	if ! test -d "${_TEMPMOUNT}/flashcast-backups/backup-${2}" ; then	
+	if ! test -d "${_TEMP_MOUNT}/flashcast-backups/backup-${2}" ; then	
 		fatal "Backup Folder backup-${2} Does not exist"
 	fi
     	# are we data? otherwise, use nandwrite.
 	if test "${1}" = "userdata" ; then
-		_RESTOREIMAGE="${_TEMPMOUNT}/flashcast-backups/backup-${2}/${1}.zip"
+		_RESTOREIMAGE="${_TEMP_MOUNT}/flashcast-backups/backup-${2}/${1}.zip"
 		dry_run "Would restore ${1} from ${_RESTOREIMAGE}"
 		if test -z "$DRY_RUN" ; then
 			if ! test -f "${_RESTOREIMAGE}" ; then	
@@ -213,7 +213,7 @@ restore_mtd_partition() {
 			fi
 		fi
 	else
-		_RESTOREIMAGE="${_TEMPMOUNT}/flashcast-backups/backup-${2}/${1}.img"
+		_RESTOREIMAGE="${_TEMP_MOUNT}/flashcast-backups/backup-${2}/${1}.img"
 		dry_run "Would restore ${1} from ${_RESTOREIMAGE}"
 		if test -z "$DRY_RUN" ; then
 			if ! test -f "${_RESTOREIMAGE}" ; then	
@@ -229,7 +229,7 @@ restore_mtd_partition() {
 	fi
 
 	#Do our own Cleanup
-	umount ${_TEMPMOUNT} && rm -r ${_TEMPMOUNT}
+	umount ${_TEMP_MOUNT} && rm -r ${_TEMP_MOUNT}
 }
 
 # flash_mtd_partition
